### ISSUE TITLE
Testing issue

### ISSUE THREAD

**Issue by coryhouse** [bendup/pluralsight-react-demo#1]
The test fails because your component is being wrapped in connect, so the find for ConnectedChild fails. If you instead import the unconnected component, you'll see the test succeeds.

// ConnectedChild.js
`export class ConnectedChild extends React.Component {`

// StatelessParent.js
`import {ConnectedChild} from './ConnectedChild';`

I know this changes your code, but to test a connected component, it's recommended to export and test the unconnected version. http://redux.js.org/docs/recipes/WritingTests.html#connected-components

**Comment by coryhouse** [comment]
Relevant spot from their docs:

> However, when you import it, you're actually holding the wrapper component returned by connect(), and not the App component itself. If you want to test its interaction with Redux, this is good news: you can wrap it in a <Provider> with a store created specifically for this unit test.

**Comment by bendup** [comment]
Cory, Thanks for taking so much time on this issue. I do however still have an issue. If I follow your advise and use the unconnected component in my stateless parent then the child component is not connected to redux and therefore does not get rendered correctly. So I have two choices: Either I have a passing unit test ,but the production code does not work or I use the connected component in my production code and the unit test fails. I have added some state related code to the connected client to demonstrate.

**Comment by coryhouse** [comment]
Understood. I'm not suggesting you keep my change. You can use the test provider to test a connected component. Then you can test a connected component. Keep in mind the reason your test was failing is because it asserts that it's working with unconnected component. So gotta either change your test or your code.

**Comment by bendup** [comment]
OK so if I understand you correctly : Even though the component I am testing is a stateless component I should still test it as if I am testing a connected component since one of its children is a connected component otherwise even a shallow render will fail?

**Comment by bendup** [comment]
Changing that second test to:

it('contains a ConnectedChild',() => {
    let wrapper = mount(
      <Provider store={store}>
        <StatelessParent />
      </Provider>
    );
    expect(wrapper.find('ConnectedChild').length).toBe(1);
  });

does make the production code and test both work. Thanks a million for the advice.

**Comment by coryhouse** [comment]
Glad you're rolling! 👍
